name: Automated release

on:
  schedule:
    - cron: "20 * * * *"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: Checkout code
        
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Automated release
        uses: mikeal/merge-release@v4.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
