name: Continuous deployment

on:
  push:
    branches:
      - master
  schedule:
    - cron: "5 * * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Set up Volta
        uses: rwjblue/setup-volta@v1

      - name: Set up build cache (yarn)
        uses: actions/cache@preview
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install

      - name: Run doc fetcher process
        run: yarn start

      - name: Commit any changes
        uses: sivakumar-kailasam/git-auto-commit-action@master
        with:
          commit_message: "docs: Add newly identified js doc"
          branch: ${{ github.head_ref }}
          # Optional glob pattern of files which should be added to the commit
          file_pattern: docs/**/*.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
