name: Continuous deployment

on:
  push:
    branches:
      - master
  schedule:
    - cron: "5 * * * *"

jobs:
  add-new-docs:
    name: Add new docs
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      CI: true

    steps:
      - name: Set up Volta
        uses: rwjblue/setup-volta@v1

      - name: Set up build cache (yarn)
        uses: actions/cache@preview
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install

      - name: Run doc fetcher process
        run: yarn start

      - name: Commit any changes
        uses: sivakumar-kailasam/git-auto-commit-action@master
        with:
          commit_message: "docs: Add newly identified js doc"
          branch: ${{ github.head_ref }}
          # Optional glob pattern of files which should be added to the commit
          file_pattern: docs/**/*.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release package
    runs-on: ubuntu-latest
    needs: add-new-docs
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Volta
        uses: rwjblue/setup-volta@v1

      - name: Install dependencies
        run: yarn install

      - name: Run semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
