name: Scheduled runs

on:
  schedule:
    - cron: '5 * * * *'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: Checkout code

      - uses: actions/setup-node@v1
        name: Setup Node.js
        with:
          node-version: 12

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Run doc fetcher process
        uses: Borales/actions-yarn@v2.0.0
        with:
          cmd: start

      - name: Commit any changes
        uses: sivakumar-kailasam/git-auto-commit-action@master
        with:
          commit_message: 'docs: Add newly identified js doc'
          branch: ${{ github.head_ref }}
          # Optional glob pattern of files which should be added to the commit
          file_pattern: docs/**/*.json

      - name: Release
        run: npx semantic-release
