name: Node CI

on: 
  schedule: 
    - cron: '2 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: npm 
      run: npx hello-world-npx
      env:
        CI: true
