name: Scheduled runs

on:
  schedule:
    - cron: '* * * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: Checkout code

      - name: Cache node modules
        uses: actions/cache@preview
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        uses: Borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Run doc fetcher process
        uses: Borales/actions-yarn@v2.0.0
        with:
          cmd: start

      - name: Commit any changes
        uses: stefanzweifel/git-auto-commit-action@v2.2.0
        with:
          commit_message: Add newly identified js doc
          branch: ${{ github.head_ref }}
          # Optional glob pattern of files which should be added to the commit
          file_pattern: docs/**/\*.json
